Add support for notebooks

diff --git a/templates/makefile.j2 b/templates/makefile.j2
--- a/templates/makefile.j2
+++ b/templates/makefile.j2
@@ -37,6 +37,20 @@ test-with-coverage-without-precompiled-code: doc
 	echo 'LoadPackage("profiling"); OutputJsonCoverage("stats_no_precompiled_code", "coverage_no_precompiled_code.json");' | gap --quitonbreak
 
 {% endif %}
+{% if has_notebooks %}
+test-notebooks:
+	cd examples/notebooks/; \
+	for filename in *.ipynb; do \
+		jupyter nbconvert --ExecutePreprocessor.kernel_name=julia-$$(julia -e 'print(VERSION.major); print("."); print(VERSION.minor)') --ExecutePreprocessor.record_timing=False --to notebook --execute "$$filename" --output=out; \
+		# remove "ipynb" extension to exclude this from loops in reruns in case the diff fails \
+		mv out.ipynb out; \
+		cat "$$filename" | grep -v '"version": "' | grep -v 'CapAndHomalg v' > modified_in; \
+		cat out | grep -v '"version": "' | grep -v 'CapAndHomalg v' > modified_out; \
+		diff modified_in modified_out || exit 1; \
+		rm modified_in out modified_out; \
+	done
+
+{% endif %}
 test-spacing:
 	grep -R "[^ [\"]  " gap/*.gi && echo "Duplicate spaces found" && exit 1 || exit 0
 	grep -RE '[^ ] +$$' gap/* && echo "Trailing whitespace found" && exit 1 || exit 0
@@ -60,4 +74,4 @@ test-spacing:
 	rm spacing_diff
 	rm spacing_diff_no_blanks
 
-ci-test: test-basic-spacing{% if not (package.tests_only_basic | default(false)) %} test-spacing test-doc{% endif %} test-with-coverage{% if has_precompiled_categories %} test-with-coverage-without-precompiled-code{% endif %}
+ci-test: test-basic-spacing{% if not (package.tests_only_basic | default(false)) %} test-spacing test-doc{% endif %} test-with-coverage{% if has_precompiled_categories %} test-with-coverage-without-precompiled-code{% endif %}{% if has_notebooks %} test-notebooks{% endif %}
