Always use --quitonbreak when running GAP

diff --git a/templates/makefile.j2 b/templates/makefile.j2
--- a/templates/makefile.j2
+++ b/templates/makefile.j2
@@ -1,3 +1,6 @@
+# make sure gap --quitonbreak fails even if it is part of a pipe
+SHELL=/bin/bash -o pipefail
+
 all: doc test
 
 doc: doc/manual.six
@@ -18,18 +21,18 @@ test-tabs:
 	! grep -RP "\t" examples/ gap/
 
 test-doc: doc
-	gap makedoc_with_overfull_hbox_warnings.g | perl -pe 'END { exit $$status } $$status=1 if /#W/;'
+	gap --quitonbreak makedoc_with_overfull_hbox_warnings.g | perl -pe 'END { exit $$status } $$status=1 if /#W/;'
 
 test-with-coverage: doc
 	gap --quitonbreak --cover stats tst/testall.g
-	echo 'LoadPackage("profiling"); OutputJsonCoverage("stats", "coverage.json");' | gap
+	echo 'LoadPackage("profiling"); OutputJsonCoverage("stats", "coverage.json");' | gap --quitonbreak
 
 test-spacing:
 	grep -R "[^ []  " gap/*.gi && echo "Duplicate spaces found" && exit 1; \
 	for filename in gap/*; do \
 		echo $$filename; \
 		grep -E '[^ ] +$$' $$filename && echo "Trailing whitespace found" && exit 1; \
-		echo "LoadPackage(\"{{ package_name }}\"); SizeScreen([4096]); func := ReadAsFunction(\"$$filename\"); FileString(\"gap_spacing\", PrintString(func));" | gap --banner; \
+		echo "LoadPackage(\"{{ package_name }}\"); SizeScreen([4096]); func := ReadAsFunction(\"$$filename\"); FileString(\"gap_spacing\", PrintString(func));" | gap --quitonbreak --banner; \
 		echo -e "\033[0m"; \
 		cat "gap_spacing" | sed 's/^function ( ) //g' | sed 's/ return; end$$//g' | sed 's/;/;\n/g' > modified_gap_spacing; \
 		cat "$$filename" | grep -v "^ *[#]" | sed 's/^ *//' | grep -v "^$$" | tr "\n" " " | sed "s/;/;\n/g" | head -c -1 > modified_custom_spacing; \
