Retry Codecov upload indefinitely

diff --git a/templates/upload_codecov.sh.j2 b/templates/upload_codecov.sh.j2
--- a/templates/upload_codecov.sh.j2
+++ b/templates/upload_codecov.sh.j2
@@ -25,8 +25,14 @@ shasum -a 256 -c codecov.SHA256SUM
 chmod +x codecov
 {% if is_meta_package %}
 {% for doc_package in doc_packages -%}
-./codecov -Z -v -s ../ -F {{ doc_package.name }} || (sleep 60; ./codecov -Z -v -s ../ -F {{ doc_package.name }} || (sleep 60; ./codecov -Z -v -s ../ -F {{ doc_package.name }}))
+while ! ./codecov -Z -v -s ../ -F {{ doc_package.name }}; do
+    echo "Codecov upload failed, retrying in 60s"
+    sleep 60
+done
 {% endfor %}
 {% else %}
-./codecov -Z -v -s ../ || (sleep 60; ./codecov -Z -v -s ../ || (sleep 60; ./codecov -Z -v -s ../))
+while ! ./codecov -Z -v -s ../; do
+    echo "Codecov upload failed, retrying in 60s"
+    sleep 60
+done
 {% endif %}
